function Data = read_in_jpk_real_time_oscilloscope_data()
%'X:\AFM DATA\MMLabRawData\ManuelR\2022_01_31_AFM-Head_Issues_ForceRamps\RT-Test-CantiInAir-1minOpenHoodThenClosedHood_Approached_PNP-DB-A-2022.01.31-10.12.03.334.txt'

AllowedFiles = {'*.out;*.csv;*.txt',...
    'Valid Types (*.out,*.txt,*.csv)'};

[TempTempFile,TempPath] = uigetfile(AllowedFiles,...
    'MultiSelect','on');

Data = struct('Channels',[],...
    'FileName',[],...
    'FancyName',[],...
    'UnitName',[]);

try
    if TempTempFile == 0
        return
    end
catch
end
k = 1;
if  ~iscell(TempTempFile)
    TempFile{1} = TempTempFile;
    TempFileCell{k} = fullfile(TempPath,TempFile{1});
        FileNameCell{k} = TempFile{1};
    k = k + 1;
else
    TempFile = TempTempFile';
    for i=1:length(TempFile)
        TempFileCell{k} = fullfile(TempPath,TempFile{i});
        FileNameCell{k} = TempFile{i};
        k = k + 1;
    end
end
FullFileCell = TempFileCell;
for i=1:length(FullFileCell)
    if isequal(FullFileCell{i}(end-3:end),'.out')
        NewName = strrep(FullFileCell{i},'.out','.txt');
        copyfile(FullFileCell{i},NewName)
        FullFileCell{i} = NewName;
    end
    Data(i).Channels = readmatrix(FullFileCell{i},'Delimiter',' ','DecimalSeparator','.','NumHeaderLines',6);
    Data(i).FileName = FileNameCell{i};
    Data(i).FancyName = {...
        "Time",...
        "Cap. Sensor X",...
        "Cap. Sensor Y",...
        "Error Signal",...
        "Height",...
        "Height (measured)",...
        "Lateral Deflection",...
        "Precision 9",...
        "Vertical Deflection",...
        "X Position (Tip)",...
        "Y Position (Tip)"};
    Data(i).UnitName = {...
        's',...
        'V',...
        'V',...
        'V',...
        'm',...
        'm',...
        'V',...
        'V',...
        'N',...
        'm',...
        'm'};
end
end